### PR TITLE
SEO fixes of broken links_SLE12SP4

### PR DESCRIPTION
**Pull request by dariavladykina**
Applied broken link fixes for SEO purposes.

Changes will be done for each version separately, so no backports needed.

When opening a PR, check all versions of the documentation that your PR applies to.

- SLE 15/openSUSE Leap 15.x
  - [ ] SLE 15 SP4/openSUSE Leap 15.4 *(current `main`, no backport necessary)*
  - [ ] SLE 15 SP3/openSUSE Leap 15.3
  - [ ] SLE 15 SP2/openSUSE Leap 15.2
  - [ ] SLE 15 SP1
  - [ ] SLE 15 GA
- SLE 12
  - [ ] SLE 12 SP5
  - [x] SLE 12 SP4
  - [ ] SLE 12 SP3

### PR reviewer only: Have all backports been applied?

The doc team member merging your PR will take care of backporting to older documents.
When opening a PR, do *not* set the following check box.

- [ ] all necessary backports are done

### CODE REVIEW

**Review by jfaltenbacher — APPROVED** [review]
LGTM, not sure if you should ask Meike about the best practices link

**Comment by chabowski** [comment]
Hi @dariavladykina: the virtualization best practices guide is not under my responsibility, even if it is called "best practices" ;-). It was there and had that name before we started the SBP series. As far as I know, @tbazant cares for virtualization. You might better want to check with him. Thanks very much!

**Comment by dariavladykina** [comment]
Hi Meike, thanks! Forwarding to Tomas now 🙂

D.
________________________________

**Review by tbazant — APPROVED** [review]
LG

**Pull request merged**
