### PR TITLE
Add information about tags and metainformation in SLE base images

### PR DESCRIPTION
**Pull request by Vogtinator**
Be more explicit about differences between SLE 12 and 15+ and clarify
some statements.

### Description
I'm sure there's a FATE/JIRA/WHATEVER about this somewhere, but could not find it...

### Checklist
*Are backports required?*

- [X] To maintenance/SLE12SP4
- [X] To maintenance/SLE15SP0
- [X] To maintenance/SLE15SP1

### CODE REVIEW

**Comment by Vogtinator** [comment]
> The `&nbsp;` entity is unnecessary.

Which ones? For the product name `&nbsp;` is used throughout doc-sle.

**Comment by cjschroder** [comment]
> > The `&nbsp;` entity is unnecessary.
> 
> Which ones? For the product name `&nbsp;` is used throughout doc-sle.

I am wrong, they are needed to prevent line breaks in the product name & version. Thank you for the PR!

**Comment by Vogtinator** [comment]
It looks like this wasn't backported to 12 SP4 yet, is that work in progress?

**Comment by cjschroder** [comment]
Sorry, I will check on backports & take care of them.

**Pull request merged**
