### PR TITLE
Jufa/sle micro 53 translations

### PR DESCRIPTION
**Pull request by jfaltenbacher**
Delivery of SLE Micro 5.3 translations

new PR created because of corrupt PR https://github.com/SUSE/doc-sle/pull/1399/commits

Message from Patrick:
Delivery of localised XML and image assets for SLE-Micro 5.3 Deployment Guides - DE, JA and ZH-CN - via Github.

(I am not certain that the intention is to merge to MAIN branch. It was not specified.)

Regards,
Patrick

### CODE REVIEW

**Comment by jfaltenbacher** [comment]
@tomschr  can you please build the PDFs using the new stylesheets and attach here?

**Comment by tomschr** [comment]
* SLE Micro 5.3 ja-jp PDF
[book-deployment-slemicro_color_ja.pdf](https://github.com/SUSE/doc-sle/files/10011135/book-deployment-slemicro_color_ja.pdf)

* SLE Micro 5.3 zh-cn PDF
[book-deployment-slemicro_color_zh_cn.pdf](https://github.com/SUSE/doc-sle/files/10011148/book-deployment-slemicro_color_zh_cn.pdf)

**Comment by ptinley-vt** [comment]
Hi Julia and Tom.

I have QAed the Japanese and the S. Chinese PDF that Tom generated earlier. I can find no issues with the new NotoSans fonts. They look good. 
However, during the QA I found some text corruptions in the Japanese book. I have requested accurate translations from the Japanese translator and when I get them I will update the 2 XML files involved (deployment_remote.xml, deployment_prep_zseries.xml). 
Just to check how best to update the files.... Julia, should I checkout the 'jufa/sle_micro_53_translation' branch locally, update the files there, and then push them?

**Comment by jfaltenbacher** [comment]
Hi @ptinley-vt , yes, you can use this branch to check in the changes or any other further work.

**Comment by ptinley-vt** [comment]
> Hi @ptinley-vt , yes, you can use this branch to check in the changes or any other further work.

Hi Julia,

I have received the updated Japanese translations this morning, which fix the strings that had text corruptions. I've tested the PDF and the issues are now fixed.

Regards,
Patrick

**Comment by jfaltenbacher** [comment]
thank you Patrick, I run some checks and merge it

**Review by taroth21 — APPROVED** [review]
Looks good to me, thanks everybody!

**Pull request merged**
