### PR TITLE
Remove 'backend' element from AY Guide SP3

### PR DESCRIPTION
**Pull request by cjschroder**
This element applies only to SLE 15 SP4 and up

### PR creator: Description

Profile 'backend' element for SLE Micro; applies only to SLES 15SP4 and up.
Also corrections to XML tags 

Jira #DOCTEAM-525
Bugzilla #1200722

### PR creator: Which product versions do the changes apply to?

When opening a PR, check all versions of the documentation that your PR applies to.

- SLE 15/openSUSE Leap 15.x
  - [ ] SLE 15 next/openSUSE Leap next *(current `main`, no backport necessary)*
  - [ ] SLE 15 SP4/openSUSE Leap 15.4
  - [x] SLE 15 SP3/openSUSE Leap 15.3
  - [ ] SLE 15 SP2/openSUSE Leap 15.2
  - [ ] SLE 15 SP1
  - [ ] SLE 15 SP0
- SLE 12
  - [ ] SLE 12 SP5
  - [ ] SLE 12 SP4
  - [ ] SLE 12 SP3

### PR reviewer only: Have all backports been applied?

The doc team member merging your PR will take care of backporting to older documents.
When opening a PR, do *not* set the following check box.

- [ ] all necessary backports are done

### CODE REVIEW

**Comment by cjschroder** [comment]
Here is a nice PDF for reviewers:
[cha-configuration-installation-options_color_en.pdf](https://github.com/SUSE/doc-sle/files/8960199/cha-configuration-installation-options_color_en.pdf)

**Review by teclator — APPROVED** [review]
LGTM

**Comment by lvicoun** [comment]
I don't know how this commit ended up there, but the backend is not valid for Micro either as 5.1 and 5.2 are based on SP3. So I'll remove the element completly.

**Comment by teclator** [comment]
> I don't know how this commit ended up there, but the backend is not valid for Micro either as 5.1 and 5.2 are based on SP3. So I'll remove the element completly.

That makes more sense

**Pull request merged**
