### PR TITLE
update routing section name -> device

### PR DESCRIPTION
**Pull request by jkh911208**
in the documentation it says device, but in xml example it says name, i confirmed device is the one intended to use.

### PR creator: Description

fix the xml example in the official documentation

### PR creator: Are there any relevant issues/feature requests?

i don't see any

### PR creator: Which product versions do the changes apply to?

When opening a PR, check all versions of the documentation that your PR applies to.

- SLE 15/openSUSE Leap 15.x
  - [x] SLE 15 SP4/openSUSE Leap 15.4 *(current `main`, no backport necessary)*
  - [x] SLE 15 SP3/openSUSE Leap 15.3
  - [x] SLE 15 SP2/openSUSE Leap 15.2

### PR reviewer only: Have all backports been applied?

The doc team member merging your PR will take care of backporting to older documents.
When opening a PR, do *not* set the following check box.

- [ ] all necessary backports are done

### CODE REVIEW

**Comment by teclator** [comment]
> in the documentation it says device, but in xml example it says name, i confirmed device is the one intended to use.

You are right, it was my fault and basically inherited the error from previous example.

See https://github.com/SUSE/doc-sle/pull/919/files

So, we should fix the element also in:

https://github.com/SUSE/doc-sle/blob/f5d6a76b8145445e992b5cd9ddda112b482aeb40/xml/ay_networking.xml#L132-L149

> ### PR creator: Description
> 
> fix the xml example in the official documentation
> ### PR creator: Are there any relevant issues/feature requests?
> 
> i don't see any
> ### PR creator: Which product versions do the changes apply to?
> 
> When opening a PR, check all versions of the documentation that your PR applies to.
> 
>     * SLE 15/openSUSE Leap 15.x
>       
>       * [x]  SLE 15 SP4/openSUSE Leap 15.4 _(current `main`, no backport necessary)_
>       * [x]  SLE 15 SP3/openSUSE Leap 15.3
>       * [x]  SLE 15 SP2/openSUSE Leap 15.2
> 
> 
> ### PR reviewer only: Have all backports been applied?
> 
> The doc team member merging your PR will take care of backporting to older documents.
> When opening a PR, do _not_ set the following check box.
> 
>     * [ ]  all necessary backports are done

**Comment by jkh911208** [comment]
@teclator everything fixed

**Comment by cjschroder** [comment]
Thank you @jkh911208 and @teclator! It LGTM, is this ready to merge?

**Comment by cjschroder** [comment]
Merging and backporting!

**Comment by cjschroder** [comment]
SLE 15 SP3: d1e209fb4 1c2b26ab5
SLE 15 SP2: d03b243bd

**Pull request merged**
