### PR TITLE
Modernize admin line graphics

### PR DESCRIPTION
**Pull request by janajaeger**
### PR creator: Description

Update all line graphics in Admin Guide according to the current brand guidelines. 

### PR creator: Which product versions do the changes apply to?

Target version is current main. Do not backport. Also include as PNG only.

### CODE REVIEW

**Comment by cwickert** [comment]
I suggest to rearrange the shapes so you can only use straight arrows.

**Comment by janajaeger** [comment]
@tbazant If Confluence is right, you are the high and mighty owner of the Admin Guide. I wanted to get your OK, before I merge this one ;) So, if you have any comments, just let me know. Thanks a million!

**Review by tbazant — APPROVED** [review]
Looks perfect!

**Comment by tbazant** [comment]
> @tbazant If Confluence is right, you are the high and mighty owner of the Admin Guide. I wanted to get your OK, before I merge this one ;) So, if you have any comments, just let me know. Thanks a million!

Thank you Jana, looks very good :-)

**Pull request merged**
