### PR TITLE
Cryptctl ha cluster

### PR DESCRIPTION
**Pull request by varkoly**
### 
There is a JIRA request to make HA envinroment for cryptcl: https://jira.suse.com/browse/PED-1326
An crmsh-script was written to make a cluster setup easy.
This document enhancement describes the usage of this script and how to setup a HA environment for cryptctl.

### Feature requests?

* jsc#PED-1326

### Which product versions do the changes apply to?

- SLE 15/openSUSE Leap 15.x
  - [x] SLE 15 next/openSUSE Leap next *(current `main`, no backport necessary)*
  - [ ] SLE 15 SP4/openSUSE Leap 15.4
  - [ ] SLE 15 SP3/openSUSE Leap 15.3
  - [ ] SLE 15 SP2/openSUSE Leap 15.2
  - [ ] SLE 15 SP1
  - [ ] SLE 15 SP0
- SLE 12
  - [ ] SLE 12 SP5
  - [ ] SLE 12 SP4

### CODE REVIEW

**Comment by varkoly** [comment]
Thanks a lot for the correcture. I agree.

**Comment by taroth21** [comment]
@dariavladykina : The feedback by @varkoly on my changes is integrated now. Handing over to you for final review and style check. Thanks!

**Review by dariavladykina — COMMENTED** [review]
Hi, just a couple of minor corrections. Thanks!

**Comment by taroth21** [comment]
@varkoly : Please have a look at Daria's changes and if you are fine with them, I'll merge this on Tue.

**Comment by varkoly** [comment]
@taroth21 Thanks a lot. Your changes are OK for me. I've learned again :-)

**Pull request merged**
