### PR TITLE
Add a NFS section to AutoYaST handbook

### PR DESCRIPTION
**Pull request by joseivanlopez**
### Description

This PR adds information about setting up a NFS drive for AutoYaST installation.

Relevant links:

* https://github.com/yast/yast-storage-ng/pull/896
* https://bugzilla.suse.com/show_bug.cgi?id=1130256

### Checklist
*Check all items that apply.*

*Are backports required?*

- [ ] To maintenance/SLE12SP3
- [ ] To maintenance/SLE12SP4
- [x] To maintenance/SLE15SP0

### CODE REVIEW

**Comment by cwickert** [comment]
Hi @joseivanlopez, the content looks good, but needs some cosmetic fixes. I will take care of them, you shouldn't need to bother with DocBook tags etc.

I'm struggling with the first sentence though: Is this only for the installation or is the configured share available in the installed system, too? I mean, you are not installing **over** NFS (the installation sources are not on NFS) but onto an NFS share, right?

**Comment by joseivanlopez** [comment]
> Hi @joseivanlopez, the content looks good, but needs some cosmetic fixes. I will take care of them, you shouldn't need to bother with DocBook tags etc.
> 

Ok, thanks a lot for taking care.

> I'm struggling with the first sentence though: Is this only for the installation or is the configured share available in the installed system, too? I mean, you are not installing **over** NFS (the installation sources are not on NFS) but onto an NFS share, right?

Yes, the idea is to use an NFS share as "destination" of the installation. Basically, your new system will be installed onto the NFS share instead of a local disk. Nothing special happens regarding the installation sources, they are the same as a regular installation.

**Comment by joseivanlopez** [comment]
@cwickert I have "cherry-picked" your PR. Moreover, after our review meeting today, we have agreed to include some references between both sections related to NFS, see the last commit.

**Comment by cwickert** [comment]
Thanks, these were excellent changes! I just rephrased two sentences a bit to confirm with the way we refer to additional information ("For more information about foo, refer to bar"), but that's was it.

Since I merged this manually, I'm now closing this PR. Thanks a lot for your input!

**Pull request closed without merging**
