### PR TITLE
security_ssh.xml - sshd_config was named sshd_configuration

### PR DESCRIPTION
**Pull request by maghiel**
security_ssh.xml - sshd_config was named sshd_configuration in the sftp section

### PR creator: Description

Apologies for the extra branch. Would I've spotted this earlier I would have created a more general branch. 
Anyway: another bug in naming: sshd_config was named sshd_configuration in the section about sftp (22.16.2).

### PR creator: Are there any relevant issues/feature requests?

Not that I know off.

### PR creator: Which product versions do the changes apply to?

When opening a PR, check all versions of the documentation that your PR applies to.

- SLE 15/openSUSE Leap 15.x
  - [ ] SLE 15 next/openSUSE Leap next *(current `main`, no backport necessary)*
  - [x] SLE 15 SP5/openSUSE Leap 15.5
  - [ ] SLE 15 SP4/openSUSE Leap 15.4
  - [ ] SLE 15 SP3/openSUSE Leap 15.3
  - [ ] SLE 15 SP2/openSUSE Leap 15.2

- SLE 12
  - [ ] SLE 12 SP5

### PR reviewer only: Have all backports been applied?

The doc team member merging your PR will take care of backporting to older documents.
When opening a PR, do *not* set the following check box.

- [ ] all necessary backports are done

### CODE REVIEW

**Comment by maghiel** [comment]
@cwickert maybe something for you to review? :)

**Comment by Amrita42** [comment]
Thanks for raising this bug @maghiel .
Thanks @taroth21 for bringing this to my attention.   
**Initial findings on my VM:**
This change is required for main/15.5 , and all 15 versions as well as SLE12 SP5 .
(will confirm as soon as I finish testing)
So far I ve tested on a:
SLE 15.5
SLE 15.2
SLE 12 SP5 

In progress:
15.4
15.3
15.1

**Comment by Amrita42** [comment]
Can confirm that this change is applicable to all the above versions. (Has been tested and verified)

**Comment by Amrita42** [comment]
Merged into all the respective versions.

**Pull request merged**
