### PR TITLE
Set dm:translation tag to yes

### PR DESCRIPTION
**Pull request by tomschr**
Created branch for translation

"Failed" XML files which needs manual check:

```
xml/art_virtualization-best-practices.xml
xml/ay_12_migrate_15.xml
xml/ay_auto_installation.xml
xml/ay_general_options.xml
xml/ay_partitioning.xml
xml/ay_registration_extensions.xml
xml/common_authors.xml
xml/container_guide_authors.xml
xml/deployment_firstboot.xml
xml/deployment_prep_zseries_prep_i.xml
xml/deployment_yast_installer.xml
xml/file_management.xml
xml/net_proxy.xml
xml/qemu_running_vms_qemukvm.xml
xml/rmt_backup.xml
xml/security_ldap_sssd.xml
xml/vt_guestfs.xml
```

### CODE REVIEW

**Comment by fsundermeyer** [comment]
Please do not merge, this is only needed temporarily. Keeping PR for now to avoid an accidental branch removel.

**Comment by sknorr** [comment]
@tomschr I am guessing this is no longer relevant..? Can we close this/delete the branch?

**Comment by sknorr** [comment]
@fsundermeyer @tomschr I am guessing this is no longer relevant..? Can we close this/delete the branch?

**Comment by fsundermeyer** [comment]
was only temporarily needed, closing without merging

**Pull request closed without merging**
