### PR TITLE
Updated feature comparison table (bsc#1222686)

### PR DESCRIPTION
**Pull request by tbazant**
### PR creator: Are there any relevant issues/feature requests?

* bsc#1222686

### PR creator: Which product versions do the changes apply to?

When opening a PR, check all versions of the documentation that your PR applies to.

- SLE 15/openSUSE Leap 15.x
  - [x] SLE 15 next/openSUSE Leap next *(current `main`, no backport necessary)*
  - [x] SLE 15 SP5/openSUSE Leap 15.5
  - [x] SLE 15 SP4/openSUSE Leap 15.4
  - [x] SLE 15 SP3/openSUSE Leap 15.3
  - [x] SLE 15 SP2/openSUSE Leap 15.2

- SLE 12
  - [ ] SLE 12 SP5

### PR reviewer only: Have all backports been applied?

The doc team member merging your PR will take care of backporting to older documents.
When opening a PR, do *not* set the following check box.

- [ ] all necessary backports are done

### CODE REVIEW

**Comment by wstephenson** [comment]
what about the expanded RHEL support (Liberty Linux), and the removal of the option to run in a container?

**Review by dariavladykina — COMMENTED** [review]
LGTM!

**Comment by tbazant** [comment]
> what about the expanded RHEL support (Liberty Linux), and ~the removal of the option to run in a container~?
> 
> That last part sounds drastic - it should be "the option to run using docker-compose is not mentioned; running inside k8s is the supported production container solution".

was this a rhetorical question or should i expect further changes? In the former case, I'll merge and close this one. Let me know please

**Comment by wstephenson** [comment]
> > what about the expanded RHEL support (Liberty Linux), and ~the removal of the option to run in a container~?
> > That last part sounds drastic - it should be "the option to run using docker-compose is not mentioned; running inside k8s is the supported production container solution".
> 
> was this a rhetorical question or should i expect further changes? In the former case, I'll merge and close this one. Let me know please

No rhetoric - lines 26 and 44 at the PR linked from the bug:
https://github.com/SUSE/rmt/pull/1119/files#diff-49c49f12d3beb8e04d2082aedb464c1be6dd2a28e4a3dd1c68437b8616fa0c6fR26

**Comment by tbazant** [comment]
> > > what about the expanded RHEL support (Liberty Linux), and ~the removal of the option to run in a container~?
> > > That last part sounds drastic - it should be "the option to run using docker-compose is not mentioned; running inside k8s is the supported production container solution".
> > 
> > 
> > was this a rhetorical question or should i expect further changes? In the former case, I'll merge and close this one. Let me know please
> 
> No rhetoric - lines 26 and 44 at the PR linked from the bug: https://github.com/SUSE/rmt/pull/1119/files#diff-49c49f12d3beb8e04d2082aedb464c1be6dd2a28e4a3dd1c68437b8616fa0c6fR26

oooh, i must have missed that one :-) is the following OK?
image
image

**Review by wstephenson — APPROVED** [review]
lgtm

**Pull request merged**
