### PR TITLE
vt-doc: Remove section on supported host environments

### PR DESCRIPTION
**Pull request by jfehlig**
### PR creator: Description

The vt-doc describes how to use SLES as a hypervisor. Information about running SLES on other hypervisors should not be in the vt-doc.

### PR creator: Are there any relevant issues/feature requests?

* bsc#1210491

### PR creator: Which product versions do the changes apply to?

When opening a PR, check all versions of the documentation that your PR applies to.

- SLE 15/openSUSE Leap 15.x
  - [x] SLE 15 next/openSUSE Leap next *(current `main`, no backport necessary)*
  - [x] SLE 15 SP4/openSUSE Leap 15.5
  - [x] SLE 15 SP4/openSUSE Leap 15.4
  - [x] SLE 15 SP3/openSUSE Leap 15.3
  - [ ] SLE 15 SP2/openSUSE Leap 15.2
  - [ ] SLE 15 SP1
- SLE 12
  - [ ] SLE 12 SP5
  - [ ] SLE 12 SP4

### PR reviewer only: Have all backports been applied?

The doc team member merging your PR will take care of backporting to older documents.
When opening a PR, do *not* set the following check box.

- [ ] all necessary backports are done

### CODE REVIEW

**Comment by jfehlig** [comment]
I'm not really sure where to put the removed info. Maybe in the 'Deployment Guide'? E.g. under section '3.2 Installation considerations', where it talks about installation on hardware vs virtual machine? Suggestions welcome. I'm happy to do it as part of this PR if we agree where to move the info.

**Comment by tbazant** [comment]
> I'm not really sure where to put the removed info. Maybe in the 'Deployment Guide'? E.g. under section '3.2 Installation considerations', where it talks about installation on hardware vs virtual machine? Suggestions welcome. I'm happy to do it as part of this PR if we agree where to move the info. 

@cwickert - do you think it's a good idea? If yes, can you take care.

Otherwise, the changes performed look OK.

**Comment by cwickert** [comment]
The hypervisors can be considered as a system requirement, therefor it does make sense to move it to the Deployment Guide. I still have to figure out where exactly though.

**Comment by cwickert** [comment]
I added the supported hypervisors to the deployment guide, feel free to merge.

**Pull request merged**
