### PR TITLE
Document where yast stores keyboard settings

### PR DESCRIPTION
**Pull request by mwilck**
### PR creator: Description

This used to be `/etc/sysconfig/keyboard`, but not any more. Save people looking by documenting it.

### PR creator: Are there any relevant issues/feature requests?

No

### PR creator: Which product versions do the changes apply to?

When opening a PR, check all versions of the documentation that your PR applies to.

- SLE 15/openSUSE Leap 15.x
  - [x ] SLE 15 SP4/openSUSE Leap 15.4 *(current `main`, no backport necessary)*
  - [x] SLE 15 SP3/openSUSE Leap 15.3
  - [x] SLE 15 SP2/openSUSE Leap 15.2  *(not sure)*

### PR reviewer only: Have all backports been applied?

The doc team member merging your PR will take care of backporting to older documents.
When opening a PR, do *not* set the following check box.

- [ ] all necessary backports are done

### CODE REVIEW

**Comment by cjschroder** [comment]
It is the same on Tumbleweed as well. I hate to say "maybe it is something weird on your system". But maybe it is something weird on your system :)  If you have a chance to do a clean installation or a new virtual machine, that should be helpful. I will leave this open a few more days.

**Comment by mwilck** [comment]
This is a fresh installation. But I was talking nonsense above. `/etc/sysconfig/keyboard` does exist, of course. But it isn't changed if I run `yast2 keyboard`, setting the layout. It doesn't contain information about the layout, actually. That's in `/etc/vconsole.conf`.

**Comment by mwilck** [comment]
After running `yast2 keyboard`, the only files that changed under `/etc` are

    # find /etc/ -mmin -3 -type f
    /etc/X11/xorg.conf.d/00-keyboard.conf
    /etc/vconsole.conf

**Comment by mwilck** [comment]
Tested on Leap and TW, consistently with the same results I stated in the PR.

AFAICT from the code, yast is using tools from systemd to apply these settings

    /usr/share/YaST2/lib/y2keyboard/strategies/systemd_strategy.rb:
        if Yast::Stage.initial
          # systemd is not available here (inst-sys).
          # do use --root option, running in chroot does not work (bsc#1074481)
          Yast::Execute.locally!("systemd-firstboot", "--root", Yast::Installation.destdir, "--keymap", keyboard_code)
        else
          Yast::Execute.on_target!("localectl", "set-keymap", keyboard_code)
        end

**Comment by cjschroder** [comment]
:woman_facepalming: I was using the wrong YaST module, I was using `yast sysconfig` (hardware > keyboard), not `yast keyboard`. I will take care of this, thanks for reporting it.

**Comment by cjschroder** [comment]
allrightythen @mwilck, I added a few changes. Please take a look at them, if they look OK I will merge and backport.

**Comment by mwilck** [comment]
ok, please go ahead. Thank you!!

**Comment by cjschroder** [comment]
SLE15SP3 a0f4d65f7
SLE15SP2 01e7ffab7
SLE15SP1 34f01a344
SLE15SP0 8544fbf17

**Pull request merged**
