### PR TITLE
Remove references to slaves in AutoYaST/YaST docs

### PR DESCRIPTION
**Pull request by imobachgs**
### PR creator: Description

Remove some references to "slave" in the (Auto)YaST docs. Unfortunately, the AutoYaST schema has not been changed for compatibility reasons, so some references to the master/slave terminology still remain.

### PR creator: Which product versions do the changes apply to?

When opening a PR, check all versions of the documentation that your PR applies to.

- SLE 15/openSUSE Leap 15.x
  - [X] SLE 15 SP4/openSUSE Leap 15.4 *(current `main`, no backport necessary)*
  - [ ] SLE 15 SP3/openSUSE Leap 15.3
  - [ ] SLE 15 SP2/openSUSE Leap 15.2
  - [ ] SLE 15 SP1
  - [ ] SLE 15 GA
- SLE 12
  - [ ] SLE 12 SP5
  - [ ] SLE 12 SP4
  - [ ] SLE 12 SP3

### PR reviewer only: Have all backports been applied?

The doc team member merging your PR will take care of backporting to older documents.
When opening a PR, do *not* set the following check box.

- [ ] all necessary backports are done

### CODE REVIEW

**Review by tbazant — APPROVED** [review]
looks good

**Comment by cjschroder** [comment]
Thank you Imo! I know you can't change some terminology because it is literally required, this is a good start. :+1:

**Review by cjschroder — CHANGES_REQUESTED** [review]
There is a validation error, I will take care of this & merge.

**Comment by cjschroder** [comment]
yay thank you @tomschr!

**Review by cjschroder — APPROVED** [review]

**Pull request merged**
