### PR TITLE
Move PCI DSS article from Security Guide to SUSE/doc-unversioned

### PR DESCRIPTION
**Pull request by cjschroder**
Unversioned articles are valid for a single codestream. All product
manuals for a single codestream link to the unversioned docs.

Resolves Jira DOCTEAM-519

### PR creator: Which product versions do the changes apply to?

When opening a PR, check all versions of the documentation that your PR applies to.

- SLE 15/openSUSE Leap 15.x
  - [x] SLE 15 SP4/openSUSE Leap 15.4 *(current `main`, no backport necessary)*
  - [x] SLE 15 SP3/openSUSE Leap 15.3
  - [x] SLE 15 SP2/openSUSE Leap 15.2
  - [x] SLE 15 SP1
  - [x] SLE 15 GA
- SLE 12
  - [ ] SLE 12 SP5
  - [ ] SLE 12 SP4
  - [ ] SLE 12 SP3

### PR reviewer only: Have all backports been applied?

The doc team member merging your PR will take care of backporting to older documents.
When opening a PR, do *not* set the following check box.

- [ ] all necessary backports are done

### CODE REVIEW

**Comment by cjschroder** [comment]
Here is a PDF for reviewers:
[book-security_color_en.pdf](https://github.com/SUSE/doc-sle/files/8633558/book-security_color_en.pdf)

**Comment by cjschroder** [comment]
@lvicoun This might have an impact on SLE-Micro

**Review by tomschr — APPROVED** [review]
@cjschroder Looks good, Carla! :+1: Merge it and I can publish it.

**Review by fsundermeyer — APPROVED** [review]
LGTM

**Comment by cjschroder** [comment]
SLE15SP3 a669b21dca
SLE15SP2 380493f29, 155007d9f
SLE15SP1 6a8ff852
SLE15SP0 4f9a35b63

**Pull request merged**
