### PR TITLE
Localization via itstool and .po files

### PR DESCRIPTION
**Pull request by Gianvacca**
Taking inspiration from the work done for the projects [](https://github.com/openSUSE/packages-i18n) and [](https://github.com/openSUSE/release-notes-openSUSE) I have created a Makefile to update .pot and .po files, to translate the .xml files for the book(s) of interest, and to generate a .pdf/.text/.html output.
The Makefile also requires a couple of bash script: po-selector (adapted from the homonymous script used in [release-notes](https://github.com/openSUSE/release-notes-openSUSE)) and xml-selector (totally mine, but inspired from the former).
I have also imported and adapted from [packages-i18n](https://github.com/openSUSE/packages-i18n) the script used to publish on Weblate, but I have no way to test it.

### CODE REVIEW

**Comment by svenseeberg** [comment]
@Gianvacca thank you for this PR. I asked our translation experts ( @sknorr and @fsundermeyer ) to take a look at this.

**Comment by svenseeberg** [comment]
@Gianvacca sorry that you did not receive an answer yet. We're currently very short on time. However, we feel that there is a need to be better with including the community. Therefore we welcome your suggestion. Could you please explain in a few sentences what you did in this PR? For example, we are wondering where the over 9000 files are coming from.

**Comment by svenseeberg** [comment]
I looked into some details now. The 9000 files are only the PO files plus one Makefile, the XML sources are not touched.

**Comment by Gianvacca** [comment]
Hi svenseeberg, I have approached git only recently and I am not aware of all tricks, but your solution sounds very good to me.

As for my PR, the massive number of files is due, as you noticed, to the number of PO files (number of XML sources times number of supported languages).

The Makefile is commented extensively, so you can easily grasp how to use it and how it works. It is more or less complete. It is able to: (re)generate the POT files following to a change in XML sources, update the PO files, generate the translated XML sources, validate them and generate translated output (PDF, HTML and TXT). It can even clean up obsolete POT and PO files (e.g. following to drop of some XML source).
However, there are still few decisions to make.
For instance, do we want to have translated pictures as well? The Makefile already takes into account such possibility (if the picture is not available under _[lang_code_dir]/images/src/[image_type_dir]/_, it creates a symlink to images/src/[image_type_dir]/picture) but in that case I guess that for each lang we should put _[lang_code_dir]/images/src/[image_type_dir]/*_ under version control.
Another decision concerns the destination of output files. In other words, do we want to periodically build PDF/HTML files and store them somewhere? I wanted to have the opinion of the maintainers before developing something.

**Comment by zoopster** [comment]
Is this a continuation of #99 ?

**Comment by svenseeberg** [comment]
@Gianvacca a suggestion for this PR:

Could we move all language folders into a new repository and make it a submodule that resides in the directory "locale"? That means that all language folders go into a new repo (for example github.com/openSUSE/doc-sle-translations), which I can create for this purpose. This module will then be pulled into the doc-sle as a submodule. Only the Makefile would then reside in this (doc-sle) repository.

This would separate translation commits from documentation commits and also improve the clone speed if the translations are not required.

**Comment by Gianvacca** [comment]
@svenseeberg Hi Sven, yes please, that's a very good solution.
If you do that, I will then adapt the Makefile, no problem.

**Comment by svenseeberg** [comment]
@Gianvacca cool. Look here:
* https://github.com/openSUSE/doc-sle-translations
* https://github.com/SUSE/doc-sle/pull/358

I'd suggest that you branch off from the branch ```feature/translations2``` and perform the required changes there. Then we will merge your changes back into ```feature/translations2```. From there we will take it to develop.

And lets continue the discussion in #358. Closing this PR.

**Pull request closed without merging**
