### PR TITLE
Minor fixes to 22.2 - Server hardening

### PR DESCRIPTION
**Pull request by maghiel**
### PR creator: Description

I found and fixed two minor issues in chapter 22.2 - Server hardening

### PR creator: Are there any relevant issues/feature requests?

Not that I know of

### PR creator: Which product versions do the changes apply to?

When opening a PR, check all versions of the documentation that your PR applies to.

- SLE 15/openSUSE Leap 15.x
  - [ ] SLE 15 next/openSUSE Leap next *(current `main`, no backport necessary)*
  - [X] SLE 15 SP5/openSUSE Leap 15.5
  - [ ] SLE 15 SP4/openSUSE Leap 15.4
  - [ ] SLE 15 SP3/openSUSE Leap 15.3
  - [ ] SLE 15 SP2/openSUSE Leap 15.2
  - [ ] SLE 15 SP1
- SLE 12
  - [ ] SLE 12 SP5
  - [ ] SLE 12 SP4

### PR reviewer only: Have all backports been applied?

The doc team member merging your PR will take care of backporting to older documents.
When opening a PR, do *not* set the following check box.

- [ ] all necessary backports are done

### CODE REVIEW

**Review by cwickert — APPROVED** [review]
LGTM, good catch(es)!

**Comment by maghiel** [comment]
> LGTM, good catch(es)!

Thanks :) Happy to be of help again!

**Comment by cwickert** [comment]
Backported to
maintenance/SLE15SP5 with d181b2087f40e125f79d8a7e1eee596de02c336c and 28a0e1487528e5e558c7c54df6dfeab69e6e5407
maintenance/SLE15SP4 with e16fb4bd1f15d59ffb3cb61c79c37409eb951487 and 28a0e1487528e5e558c7c54df6dfeab69e6e5407

**Comment by cwickert** [comment]
Also 
maintenance/SLE15SP3 with af7d900e6220ab8ec4069a40fed3768618c7268
maintenance/SLE15SP2 with 7a834e65444ba39145fa0b9b4cca07d9647c9607

**Pull request merged**
