### PR TITLE
Use "More information" instead of "For more information"

### PR DESCRIPTION
**Pull request by sknorr**
### Description

Update after style guide changes...

Not entirely sure if we need backports but am happy to provide them

### Are there any relevant issues/feature requests?

* [gh#SUSE/doc-styleguide#145](https://github.com/SUSE/doc-styleguide/issues/145)

### To which product versions do the changes apply?

The first column is to be filled by the requester, the second column is to be filled by the doc team after the changes have been backported to the maintenance branches.

| Code 15     | Backport Done
| ----------  | ----------
| [x] 15 SP3  | *(no backport necessary)*
| [x] 15 SP2  | [ ]
| [x] 15 SP1  | [ ]
| [x] 15 SP0  | [ ]

| Code 12     | Backport Done
| ----------  | ----------
| [x] 12 SP5  | [ ]
| [x] 12 SP4  | [ ]
| [x] 12 SP3  | [ ]
| [x] 12 SP2  | [ ]

### CODE REVIEW

**Review by taroth21 — APPROVED** [review]

**Comment by taroth21** [comment]
About the backports: I would vote for not backporting this as this was mainly triggered by the title/sentence style change for the headlines which we did not backport so far.

**Comment by sknorr** [comment]
> About the backports: I would vote for not backporting this as this was mainly triggered by the title/sentence style change for the headlines which we did not backport so far.

Well, that decreases the number of things to be done here. Can't say I am unhappy about that.

**Comment by sknorr** [comment]
Merged manually as 5a96cb3 + c39ea09

**Comment by sknorr** [comment]
@lproven If Firefox does not work, Git _does_ have a command-line interface (and there are also various desktop utilities), but for a basic review, `git diff main..feature/more-information` or just looking at the commits on this branch with `git show HASH` individually would have worked.

This kind of non-review review is not that helpful, especially after I specifically requested a review. I was hoping you were going to look at the context of the changes a bit and see if I'd maybe accidentally renamed a section that should not have been renamed etc.

**Pull request closed without merging**
