### PR TITLE
SEO link fixes_zh

### PR DESCRIPTION
**Pull request by dariavladykina**
### PR creator: Description

Updated broken links for zh_cn and zh_tw files for SEO purposes.

### PR creator: Are there any relevant issues/feature requests?

* bsc#...
* jsc#SLE-...

### PR creator: Which product versions do the changes apply to?

When opening a PR, check all versions of the documentation that your PR applies to.

- SLE 15/openSUSE Leap 15.x
  - [ ] SLE 15 SP4/openSUSE Leap 15.4 *(current `main`, no backport necessary)*
  - [ ] SLE 15 SP3/openSUSE Leap 15.3
  - [ ] SLE 15 SP2/openSUSE Leap 15.2
  - [ ] SLE 15 SP1
  - [x] SLE 15 GA
- SLE 12
  - [ ] SLE 12 SP5
  - [ ] SLE 12 SP4
  - [ ] SLE 12 SP3

### PR reviewer only: Have all backports been applied?

The doc team member merging your PR will take care of backporting to older documents.
When opening a PR, do *not* set the following check box.

- [ ] all necessary backports are done

### CODE REVIEW

**Comment by jfaltenbacher** [comment]
Hi @dariavladykina there are some validations errors happening. Please don't merge until fixed. I will check on Monday

**Review by jfaltenbacher — CHANGES_REQUESTED** [review]
validation errors need to be fixed first

**Comment by jfaltenbacher** [comment]
added @fsundermeyer as reviewer to make sure validation runs smoothly

**Comment by jfaltenbacher** [comment]
validation still reports table errors. maybe this branch needs a rebase because the changes with the l10n folders are not in here yet?

**Comment by fsundermeyer** [comment]
This has been replaced with PR #1158, do not merge. Closing.

**Pull request closed without merging**
