### PR TITLE
Virt Best Practices: add scsi persistent reservation on multipathed i/o

### PR DESCRIPTION
**Pull request by morecache**
### PR creator: Description

Describe the overall goals of this pull request.

### PR creator: Are there any relevant issues/feature requests?

* bsc#1210642
* jsc#...

### PR creator: Which product versions do the changes apply to?

When opening a PR, check all versions of the documentation that your PR applies to.

- SLE 15/openSUSE Leap 15.x
  - [ ] SLE 15 next/openSUSE Leap next *(current `main`, no backport necessary)*
  - [ ] SLE 15 SP4/openSUSE Leap 15.5
  - [ ] SLE 15 SP4/openSUSE Leap 15.4
  - [ ] SLE 15 SP3/openSUSE Leap 15.3
  - [ ] SLE 15 SP2/openSUSE Leap 15.2
  - [ ] SLE 15 SP1
- SLE 12
  - [ ] SLE 12 SP5
  - [ ] SLE 12 SP4

### PR reviewer only: Have all backports been applied?

The doc team member merging your PR will take care of backporting to older documents.
When opening a PR, do *not* set the following check box.

- [ ] all necessary backports are done

### CODE REVIEW

**Review by hw-claudio — APPROVED** [review]
lgtm

**Comment by hw-claudio** [comment]
@tbazant I don't think I can merge this, maybe your team could take a look at the form as well, and then merge if ok?

Thanks C

**Comment by tbazant** [comment]
@morecache can you please direct this PR to this branch instead of  `main` ?
https://github.com/SUSE/doc-sle/tree/tbazant-art-virt-best-practice-bsc%231210642

I will merge it and then work on style and language with our proof reader. After we do our changes, i'll let you review it once more and finally merge and publish. agree?

**Comment by morecache** [comment]
> @morecache can you please direct this PR to this branch instead of `main` ? https://github.com/SUSE/doc-sle/tree/tbazant-art-virt-best-practice-bsc%231210642
> 
done.

**Comment by tbazant** [comment]
@morecache how deep should i beckport this stuff? down to 15SP1 or even 12SP4? BTW the new PR is at https://github.com/SUSE/doc-sle/pull/1584

**Comment by morecache** [comment]
> @morecache how deep should i beckport this stuff? down to 15SP1 or even 12SP4? BTW the new PR is at #1584

We offer qemu-pr-helper program in qemu-tools package since SLES 12 SP4. Let's ask Claudio to make the decision that which SLES OSes need to be backported. @hw-claudio

**Comment by hw-claudio** [comment]
@tbazant @morecache I think we should go back to 15SP4,

and if applicable also update 12SP5 (but I am not sure if instructions need to be adapted for old qemu-3.1.1.1 and libvirt-5.1.0)

**Comment by morecache** [comment]
> and if applicable also update 12SP5 (but I am not sure if instructions need to be adapted for old qemu-3.1.1.1 and libvirt-5.1.0)

The instructions are applicable to libvirt-5.1.0 as well.

**Pull request merged**
