### PR TITLE
create new version of the audit components graphic, include as PNG only

### PR DESCRIPTION
**Pull request by janajaeger**
### PR creator: Description

Describe the overall goals of this pull request.

"Fix" for Jira DOCTEAM-720. Old audit_components graphic had problems with lines missing in action. New one has general problems with pure SVG include, but most certainly no problems with lines. So, not a fix, but a "fix" for now.

Check whether this works for you and whether this can and should be cherry-picked.

### PR creator: Which product versions do the changes apply to?

When opening a PR, check all versions of the documentation that your PR applies to.

- SLE 15/openSUSE Leap 15.x
  - [x] SLE 15 next/openSUSE Leap next *(current `main`, no backport necessary)*
  - [x] SLE 15 SP4/openSUSE Leap 15.4
  - [ ] SLE 15 SP3/openSUSE Leap 15.3
  - [ ] SLE 15 SP2/openSUSE Leap 15.2
  - [ ] SLE 15 SP1
  - [ ] SLE 15 SP0
- SLE 12
  - [ ] SLE 12 SP5
  - [ ] SLE 12 SP4

### PR reviewer only: Have all backports been applied?

The doc team member merging your PR will take care of backporting to older documents.
When opening a PR, do *not* set the following check box.

- [ ] all necessary backports are done

### CODE REVIEW

**Comment by jfaltenbacher** [comment]
I have build the pdf and image looks good to me now.
What to do with the Chinese file? Can we enter the translated text (it's just 3 strings) or use the English original file until the next translation drop? I would be fine with either one solution but the image should also be fixed for Chinese.

**Comment by janajaeger** [comment]
If you know how to enter these strings in Chinese and how to NOT convert them to a path, go for it and enter them. I for one have no clue how to do that ;) So I would just go ahead and use the English version. Not sure, why they localize at all in this graphic.

**Comment by jfaltenbacher** [comment]
ok, let's go ahead with the English version

**Comment by cjschroder** [comment]
It is pretty. I approve.

**Review by cjschroder — APPROVED** [review]

**Review by jfaltenbacher — APPROVED** [review]

**Pull request merged**
