### PR TITLE
vt-doc: Add note about PCI topology for QEMU Q35 machines

### PR DESCRIPTION
**Pull request by jfehlig**
See https://bugzilla.suse.com/show_bug.cgi?id=1175218 for details.

Signed-off-by: Jim Fehlig <jfehlig@suse.com>

### Description

Improve documentation around device hotplug.

### Are there any relevant issues/feature requests?

* bsc#1175218

### To which product versions do the changes apply?

The first column is to be filled by the requester, the second column is to be filled by the doc team after the changes have been backported to the maintenance branches.

| Code 15     | Backport Done
| ----------  | ---------- 
| [x ] 15 SP3  | (`master` only)   
| [x ] 15 SP2  | [ ] 
| [ ] 15 SP1  | [ ] 
| [ ] 15 SP0  | [ ] 

| Code 12     | Backport Done
| ----------  | ---------- 
| [ ] 12 SP5  | [ ] 
| [ ] 12 SP4  | [ ] 
| [ ] 12 SP3  | [ ] 
| [ ] 12 SP2  | [ ]

### CODE REVIEW

**Comment by dfaggioli** [comment]
FWIW, this doc change seems both useful and technically correct to me

**Comment by grisu48** [comment]
Highly appreciate this section. Thanks for adding it! :+1:

**Comment by cjschroder** [comment]
Thank you @jfehlig, much appreciate your PR! And thanks to @dfaggioli and @grisu48. Looks good to me as well, I will merge and backport.

**Comment by cjschroder** [comment]
SLE15 SP2: b01357aec

**Pull request merged**
