### PR TITLE
new keyboard description file

### PR DESCRIPTION
**Pull request by schubi2**
### Description
A few sentences describing the overall goals of this pull request.
If there are relevant Bugzilla or FATE entries, reference them.

### Checklist
* Check all items that apply.

*Are backports required?* no

### CODE REVIEW

**Comment by cjschroder** [comment]
Thanks for the PR, @schubi2! Is this change for SLES15 SP2 only?

**Comment by wfeldt** [comment]
Apart from that typo, lgtm

**Comment by cjschroder** [comment]
Thanks @schubi2 and @wfeldt, I corrected the tyop and merged. PRs are much appreciated! You also have the option of opening a github Issue, or emailing anyone on the doc team anytime you want to make a change, and we'll handle the formatting and committing.

**Comment by cjschroder** [comment]
Merging for master (SLE15 SP2) only; I don't see it in earlier releases.

**Pull request merged**
