### PR TITLE
portus: expanded the section on Portus

### PR DESCRIPTION
**Pull request by mssola**
### Description

In particular, I've added a couple of lines that should address some of
the confusions that our customers have reported.

Fixes SUSE/doc-caasp#115
Bugzilla entry: https://bugzilla.suse.com/show_bug.cgi?id=1109636

### Checks
* Check all items that apply.

*Is a Doc Update section necessary and has it been created?*

- [ ] Minor edit without associated FATE/Bugzilla: no Doc Update required
- [x] All other edits: Doc Update section has been added, in a separate commit

*Are backports required?*

- [x] To maintenance/SLE12SP3
- [x] To maintenance/SLE12SP4

### CODE REVIEW

**Comment by mssola** [comment]
@taroth21 @r0ckarong ping

**Comment by r0ckarong** [comment]
Needs some minor tweaks to adhere to the style guide but otherwise LGTM.

**Comment by mssola** [comment]
> @taroth21 Needs some minor tweaks to adhere to the style guide but otherwise LGTM.

Fixed!

**Comment by mssola** [comment]
@sknorr thanks!

**Pull request merged**
