### PR TITLE
fix minor typo

### PR DESCRIPTION
**Pull request by victorhck**
### PR creator: Description

Describe the overall goals of this pull request.
Fix a minor typo

### PR creator: Are there any relevant issues/feature requests?

* bsc#...
* jsc#SLE-...

### PR creator: Which product versions do the changes apply to?

When opening a PR, check all versions of the documentation that your PR applies to.

- SLE 15/openSUSE Leap 15.x
  - [ ] SLE 15 SP4/openSUSE Leap 15.4 *(current `main`, no backport necessary)*
  - [X] SLE 15 SP3/openSUSE Leap 15.3
  - [X] SLE 15 SP2/openSUSE Leap 15.2
  - [ ] SLE 15 SP1
  - [ ] SLE 15 GA
- SLE 12
  - [ ] SLE 12 SP5
  - [ ] SLE 12 SP4
  - [ ] SLE 12 SP3

### PR reviewer only: Have all backports been applied?

The doc team member merging your PR will take care of backporting to older documents.
When opening a PR, do *not* set the following check box.

- [ ] all necessary backports are done

### CODE REVIEW

**Review by cjschroder — APPROVED** [review]

**Comment by cjschroder** [comment]
Thank you @victorhck! I will merge and backport.

**Comment by cjschroder** [comment]
SLE15SP3 ff86602cc
SLE15SP2 404447126

**Comment by victorhck** [comment]
> Thank you @victorhck! I will merge and backport.

Great!!! Thanks to you (and doc team) for your work!!
I was thinking about to report or not this really small fix... BTW also sent a mail to doc mail about another issue found.
Kind regards

**Comment by cjschroder** [comment]
Oh yes, big or small we want them all. :)

**Pull request merged**
