### PR TITLE
v2v fixes + p2v documentation

### PR DESCRIPTION
**Pull request by cbosdo**

### CODE REVIEW

**Comment by cbosdo** [comment]
[TP: how-to on v2v (and potentially p2v)](https://trello.com/c/K4KlvAfs/310-tp-how-to-on-v2v-and-potentially-p2v)

**Comment by cbosdo** [comment]
[virt-p2v: Add physical to virtual migration tools (TechPrev)](https://trello.com/c/xJUmahPK/151-virt-p2v-add-physical-to-virtual-migration-tools-techprev)

**Comment by keichwa** [comment]
In xen2kvm_quick, this statement is unclear to me:

  <sect2 xml:id="v2v.prepare">
   <title>Preparing the Virtual Machine</title>
   <note>
    <para>
     If running <command>virt-v2v</command> on &sls; 12 SP1 or before,
     this step can be safely skipped. This step can also be ignored if the
     virtual machine is a fully virtualized one or if it runs a &sls; 12 SP2
     or earlier.
    </para>
   </note>

Especially the last part ("or if it runs a &sls; 12 SP2 or earlier.")
does not make sense to me.  What's actually meant?

-- 
Karl Eichwalder            SUSE Linux GmbH
R&D / Documentation        Maxfeldstraße 5
                           90409 Nürnberg, Germany
GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg)

**Comment by cbosdo** [comment]
The thing is that the old virt-v2v (in SLES 12SP1 and earlier) will install the default kernel on the guest, while this needs to be done manually with the new SLES 12 SP2 virt-v2v.

However you are right, the "or if it runs a &sls; 12 SP2 or earlier." should be "or if it runs a &sls; 12 SP2 or later.": thanks to the pvops kernel introduced in SP2, we already have the right kernel installed in SP2 guests. Do you want me to fix it or will you do it?

**Comment by keichwa** [comment]
Cedric Bosdonnat <notifications@github.com> writes:

> However you are right, the "or if it runs a &sls; 12 SP2 or earlier."
> should be "or if it runs a &sls; 12 SP2 or later.": thanks to the pvops
> kernel introduced in SP2, we already have the right kernel installed in
> SP2 guests. Do you want me to fix it or will you do it?

Yes, I see.  I fixed it as you described, and applied some additional
editorial changes.  I it all push now to the develop branch.  Thanks for
your input!

-- 
Karl Eichwalder            SUSE Linux GmbH
R&D / Documentation        Maxfeldstraße 5
                           90409 Nürnberg, Germany
GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg)

**Pull request merged**
