### PR TITLE
[WIP]:removes the redundant statement

### PR DESCRIPTION
**Pull request by Amrita42**
### PR creator: Description

Describe the overall goals of this pull request.

[DOCTEAM-898](https://jira.suse.com/browse/DOCTEAM-898)

### PR creator: Which product versions do the changes apply to?

When opening a PR, check all versions of the documentation that your PR applies to.

- SLE 15/openSUSE Leap 15.x
  - [x] SLE 15 next/openSUSE Leap next *(current `main`, no backport necessary)*
  - [x] SLE 15 SP5/openSUSE Leap 15.5
  - [x] SLE 15 SP4/openSUSE Leap 15.4
  - [x] SLE 15 SP3/openSUSE Leap 15.3
  - [x] SLE 15 SP2/openSUSE Leap 15.2
  - [x] SLE 15 SP1
- SLE 12
  - [ ] SLE 12 SP5
  - [ ] SLE 12 SP4

### PR reviewer only: Have all backports been applied?

The doc team member merging your PR will take care of backporting to older documents.
When opening a PR, do *not* set the following check box.

- [ ] all necessary backports are done

### CODE REVIEW

**Comment by cwickert** [comment]
@Amrita42, SUSEfirewall was removed from SLE 15 >= SP4. For older releases, it's still available. Thus, this should not be backported to anything older than SP4.

I reverted the change on SP2 and SP3. On SP1, this revert was not necessary because your commit 6fe798984663b8ccaf8c2c11bcd8debb52d398dd which claims to remove the statement actually adds it.

**Comment by Amrita42** [comment]
@cwickert I am testing on SP3/SP2/SP1and will get back on this . Because I have a comment from Marcus M, thats its not available for all SPs for SLE15
Its not a claim but rather an error on my part  :)

**Comment by fsundermeyer** [comment]
> @Amrita42, SUSEfirewall was removed from SLE 15 >= SP4. For older releases, it's still available. Thus, this should not be backported to anything older than SP4.
> 
> I reverted the change on SP2 and SP3. On SP1, this revert was not necessary because your commit [6fe7989](https://github.com/SUSE/doc-sle/commit/6fe798984663b8ccaf8c2c11bcd8debb52d398dd) which claims to remove the statement actually adds it.

@cwickert This is not entirely correct. susefirewall2 was only provided via Package Hub for SP0-SP3 (see SCC package search), so I think Amrita's patch is also valid for SP2 and SP3.

**Comment by Amrita42** [comment]
As per my testing on **SLE15 SP1-SP5**, I get the following results:
amrita@localhost:~> zypper search -i firewalld
Loading repository data...
Reading installed packages...

S  | Name           | Summary                                          | Type
---+----------------+--------------------------------------------------+--------
i+ | firewalld      | A firewall daemon with D-Bus interface providi-> | package
i  | firewalld-lang | Translations for package firewalld               | package
amrita@localhost:~> zypper search -i SuSEfirewall2
Loading repository data...
Reading installed packages...
No matching items found.
Additionally the information from Marcus Meissner(from an email i sent to security@suse.de) states:
SuSEfirewall2 was fully replaced by firewalld in SLE15.

_It is not available anymore.
There is only a migration script available, called susefirewall2-to-firewalld.
As far as I see, SuSEfirewall2 was never shipped for any SLES 15 service
pack despite above statement.  
Ciao, Marcus_
------------------------------------------------------
Based on these data points, I am going to apply the patch to SP5-SP1. 

@cwickert Being the PR owner , I would ask you **not**  to make changes to my PR , rather **suggest** them and I can take a look. Thanks!

**Comment by cwickert** [comment]
> @cwickert Being the PR owner , I would ask you **not** to make changes to my PR , rather **suggest** them and I can take a look. Thanks!

I did not make changes to your PR, I reverted your commit for on 15 SP2 and SP3 because you had already merged your changes without without anybody looking at it. If you had asked for a review, we would not have this back and forth in the repo but only discuss things in the review.

Frank is correct, SUSEfirewall is only available from Package Hub as of SLE 15 GA (means that statement, that it is available in the 'main' repo was incorrect from the beginning), nevertheless we should IHMO mention it.

**Comment by Amrita42** [comment]
@cwickert I was not aware a review was required since I am the maintainer of the security guide  and I ve confirmed the technical statement from the SME and tested it.  .unless I'am missing something in the review process/workflow.

**Pull request merged**
