### PR TITLE
AutoYaST: fix the layout description of the states tarball

### PR DESCRIPTION
**Pull request by imobachgs**
### Description

Clarifies the layout of the TAR archive you can provide to AutoYaST via the `states_url` element (related to [bsc#1168080](https://bugzilla.suse.com/show_bug.cgi?id=1168080)).

Thanks!

### Checklist
* Check all items that apply.

*Are backports required?*

- [X] To maintenance/SLE15SP1
- [ ] To maintenance/SLE15SP0
- [ ] To maintenance/SLE12SP5
- [ ] To maintenance/SLE12SP4
- [ ] To maintenance/SLE12SP3

### CODE REVIEW

**Comment by cjschroder** [comment]
Much more better, thank you! Merging and backporting.

**Comment by cjschroder** [comment]
There is no `ay_configuration_management.xml` file in SLE 15 SP1. I'll look at the AY chapter on Monday to see if there is a place for this.

**Comment by imobachgs** [comment]
Thanks! Yes, the AY documentation was splitted in several files, which is nice when working with new documentation but it makes backporting harder. :P

**Comment by cjschroder** [comment]
Yes, it is on my to-do to do the same to SP1 and SP0.

**Pull request merged**
