### PR TITLE
Docker on demand

### PR DESCRIPTION
**Pull request by cjschroder**
### Description
This is a do-over of https://github.com/SUSE/doc-sle/pull/617 because I messed it up.

### Checklist
* Check all items that apply.

*Are backports required?*

- [x] To maintenance/SLE15SP1
- [x] To maintenance/SLE15SP0
- [x] To maintenance/SLE12SP5
- [x] To maintenance/SLE12SP4
- [x] To maintenance/SLE12SP3

### CODE REVIEW

**Comment by cjschroder** [comment]
@rhafer plz take a quick look. thanks!

**Comment by rhafer** [comment]
@cjschroder LGTM, thanks!

**Comment by cjschroder** [comment]
Thanks @rhafer I will merge and backport.

**Comment by cjschroder** [comment]
@rhafer Note than the master branch is SLE 15 SP3 now. Just in case you feel like writing more PRs :)

**Comment by cjschroder** [comment]
SLE15SP2: https://github.com/SUSE/doc-sle/commit/a9dc792feebef425e1885cef0be2649835ec247a
SLE15SP1: 170a6d9db
SLE15SP0: 47f2980b1

**Comment by cjschroder** [comment]
@rhafer, for SLE12, do I replace RMT with SMT?

**Comment by rhafer** [comment]
@cjschroder I think it should stay with RMT. SLE 12 instances in the public clouds use the same services as SLE15 instances (all based in RMT).

**Comment by cjschroder** [comment]
Of course, thank you for the clarification!
SLE12SP5: 7b026018404
SLE12SP4: 3127d8c1a691
SLE12SP3: 090f7faff3be1

**Pull request merged**
