### PR TITLE
SLE15-SP2 Raspberry Pi cleanups

### PR DESCRIPTION
**Pull request by afaerber**
### Description
Address another grammar nit.

Previously the Raspberry Pi Quick Start guide had a legal footnote explaining * as third-party trademarks. This appears to have gone lost despite lots of * occurrences, so first factor them out as entities and then follow @lproven's rpireg example of using the actual trademark symbols. Take it one step further and properly mark them up in DocBook. No star should now be left in Quick Start and Deployment guides or their entities.

Add mention of MIPI DSI display interface - this had been added via ECO to SLE15 GA.

### Checklist
* Check all items that apply.

*Are backports required?*

- [ ] To maintenance/SLE15SP1
- [ ] To maintenance/SLE15SP0
- [ ] To maintenance/SLE12SP5
- [ ] To maintenance/SLE12SP4
- [ ] To maintenance/SLE12SP3

### CODE REVIEW

**Comment by cjschroder** [comment]
Allrightythen, I find no typos, and trust that you have the technical information correct. :+1:

**Comment by cjschroder** [comment]
Wait, I just caught something-- if you are intending to replace asterisks with trademark symbols, it didn't work. This is what I see when I build your PR:

raspi-asterisk

I found the copyright notice you mentioned:

````
<legalnotice>
 <para>
  Copyright &copy; [starting year]&ndash;<?dbtimestamp format="Y"?>
  SUSE LLC and contributors. All rights reserved.
 </para>
 <para>
  Permission is granted to copy, distribute and/or modify this document
  under the terms of the GNU Free Documentation License, Version 1.2 or
  (at your option) version 1.3; with the Invariant Section being this
  copyright notice and license. A copy of the license version 1.2 is
  included in the section entitled <quote>GNU Free Documentation
  License</quote>.
 </para>
 <para>
  For &suse; trademarks, see
  <link xlink:href="http://www.suse.com/company/legal/"/>.
  All other third-party trademarks are the property of their respective
  owners. Trademark symbols (&reg;, &trade; etc.) denote trademarks
  of &suse; and its affiliates. Asterisks (*) denote third-party
  trademarks.
 </para>
 <para>
  All information found in this book has been compiled with utmost
  attention to detail. However, this does not guarantee complete
  accuracy. Neither SUSE LLC, its affiliates, the authors nor the
  translators shall be held liable for possible errors or the
  consequences thereof.
 </para>
</legalnotice>


@lproven, any thoughts ?

**Comment by afaerber** [comment]
@cjschroder In my generated PDF I see this text: "SUSE, the SUSE logo and YaST are registered trademarks of SUSE LLC in the United States
and other countries. For SUSE trademarks, see http://www.suse.com/company/legal/ . Linux is a
registered trademark of Linus Torvalds. Other names or trademarks mentioned in this document
may be trademarks or registered trademarks of their respective owners.
All information found in this book has been compiled with utmost attention to detail. However,
this does not guarantee complete accuracy. Neither SUSE LLC, its affiliates, the authors, nor the
translators shall be held liable for possible errors or the consequences thereof."

I'd be happy to help revert to a star if preferred, the individual commits should help with that. I would just ask to use the same scheme in both documents, so that we can share the entities.

I made the experience that I needed to run `daps ... clean` before changes in the entity declaration file would show up in the PDF when no simultaneous change was done to the XML file.

**Comment by lproven** [comment]
I must admit I do **not** like the use of the asterisk. I keep looking for footnotes that are not there.

Either ™ or ® seem preferable to me. 

e.g.
[trademark class='registered']WebSite[/trademark]

**Comment by afaerber** [comment]
Just verified that master branch PDF is building fine here - no * footnote text, and (R) and SM (as third symbol) showing as expected.

**Comment by cjschroder** [comment]
My mistake, it does show the trademark symbols. I forgot to update my local branch. No asterisks. Thanks and carry on!

**Pull request merged**
