### PR TITLE
Kernel live patching: Replace KLP image with DITAA version

### PR DESCRIPTION
**Pull request by sknorr**
### PR creator: Description

This replaces the PNG version and the incompatible SVG version of the Kernel Live Patching image with a DITAA version.
What it looks like when rendered:

DITAA

This is partly an attempt to see how editing works. (I guess Emacs org mode would have helped. I also missed block selection in my editor.)

I do agree that it does not quite have the graphical fidelity of the original version:
original PNG

### PR creator: Are there any relevant issues/feature requests?

* jsc#DOCTEAM-191

### PR creator: Which product versions do the changes apply to?

When opening a PR, check all versions of the documentation that your PR applies to.

- SLE 15/openSUSE Leap 15.x
  - [ ] SLE 15 SP4/openSUSE Leap 15.4 *(if applicable to 15 SP4 _only_ -- do not merge yet!)*
  - [ ] SLE 15 SP3/openSUSE Leap 15.3 *(current `main`, no backport necessary)*
  - [ ] SLE 15 SP2/openSUSE Leap 15.2
  - [ ] SLE 15 SP1
  - [ ] SLE 15 GA
- SLE 12
  - [ ] SLE 12 SP5
  - [ ] SLE 12 SP4
  - [ ] SLE 12 SP3

### PR reviewer only: Have all backports been applied?

The doc team member merging your PR will take care of backporting to older documents.
When opening a PR, do *not* set the following check box.

- [ ] all necessary backports are done

### CODE REVIEW

**Review by lproven — APPROVED** [review]

**Review by dmpop — CHANGES_REQUESTED** [review]
Two questions:

1. Are you going to redo _all_ diagrams made with draw.io? Because if you are not, then what's the point?
2. Were there any discussions about using DITAA for diagramming?

**Comment by sknorr** [comment]
> 1. Are you going to redo all diagrams made with draw.io? Because if you are not, then what's the point?

The point was for me to actually create a DITAA image. The other point was to get you (and others) to look at DITAA and see whether it makes sense to you.
I was not going to re-create all diagrams. At least not right at this point.


> 2. Were there any discussions about using DITAA for diagramming?

Essentially, this is the discussion. Or the start of a discussion.

**Comment by dmpop** [comment]
I mean, if you want us to take a look at DITAA and start a discussion, filing a PR request might not be the best course of action. Bring it up an weekly call?

**Comment by sknorr** [comment]
Ok, whatever. I don't need this, I guess.

**Comment by janajaeger** [comment]
ditaa seems perfect for flowcharts and the likes, but there are a few drawbacks which we must consider:
- no option to change the default font - there seems to be a patch somewhere to support just that
- arrow heads default to a design not compatible with (current) SUSE style (proposed fix: ignore and live with it?)
- line color defaults to black - we need an option to colorize lines (just using dashes instead doesn't cut it)

But a PR is not the right place to discuss this. Will bring it up in one of the next meetings.

**Pull request closed without merging**
