### PR TITLE
Change IDs for better SEO

### PR DESCRIPTION
**Pull request by sknorr**
### Description
For the new documentation pages, we'd like to provide more SEO-friendly IDs. Unfortunately, that means replacing `.` and `_` with `-`

### Checklist
* Check all items that apply.

*Are backports required?*

Yes, to all branches but will be done manually.

### CODE REVIEW

**Comment by sknorr** [comment]
As an idea for how to review this, this might be relevant:

```
git show develop..feature/id-changes | sed -n '/^[-+] [^<>]*$/ p'
```

**Comment by taroth21** [comment]
@sknorr : Thanks, Stefan! I've glimpsed at the changes in some of the files and did not spot anything that seems weird or incorrect to me, so let's give it a go. Th

**Comment by sknorr** [comment]
So, I've decided to wait until tomorrow merging this. I'd like to double-check build results.

**Comment by sknorr** [comment]
I have made those changes again, directly on develop. This is now irrelevant.

**Pull request closed without merging**
