### PR TITLE
added salt module

### PR DESCRIPTION
**Pull request by schubi2**

### CODE REVIEW

**Comment by imobachgs** [comment]
LGTM. Let's wait for the documentation team. Thanks!

**Comment by sknorr** [comment]
Are you sure that abbreviating "Configuration Management System" as CMS is a good idea? Personally, I find it a bit dangerous to redefine an abbreviation that is very widely used for "Content Management System".

Also see https://en.wikipedia.org/wiki/CMS#Computing which provides multiple resolutions of the abbreviation but does not mention "Configuration Management System" (yet).

**Comment by imobachgs** [comment]
Good point. Yes, we probably need to find a better acronym. In the section you mention, I can read:

*Configuration management system, now known as software configuration management*

So what about SCM? The problem is that it's also the acronym for *source control management*. With a three-letters acronym we have a high chance to collide :)

**Comment by sknorr** [comment]
Can you avoid using an acronym here? I know that makes some sentences longer but still... maybe just "Configuration Management" would suffice?
Afaics, this is what our SUSE Manager docs are using ( https://github.com/SUSE/doc-susemanager ).

**Comment by sknorr** [comment]
Thanks!

**Pull request merged**
