### PR TITLE
docker: add notes about building in on-demand cloud instances

### PR DESCRIPTION
**Pull request by rhafer**
### Description
Building in "pay-as-you-go" or "on-demand" instances will require
addtional preparations, because of some specialities in the update
infrastructure. Add a note about that.

### Checklist
*Are backports required?*

- [x] To maintenance/SLE15SP1
- [x] To maintenance/SLE15SP0
- [x] To maintenance/SLE12SP5
- [x] To maintenance/SLE12SP4
- [x] To maintenance/SLE12SP3

### CODE REVIEW

**Comment by rhafer** [comment]
This is mostly copied from https://github.com/SUSE/container-suseconnect/commit/d299b284d3e1cab23eac96112e79ea34c4a4ec41

Please do not merge this yet, as the required changes in the public cloud images haven't been released yet. But I'd like to get some feedback. 

Also I am not entirely sure if I made correct usage of all the SLE , rmt tags and other markup. It might also make sense to rework the entire section a bit as it now contains there "Note" section in a row. Feel free to push additional changes to this.

**Comment by rhafer** [comment]
Remove the node about not merging as the updates for the public cloud images have been submitted meanwhile.

**Comment by cjschroder** [comment]
Hello @rhafer, thank you for this! I made a few changes, corrected some markup and smoothing out some of the wording. Will you take a look and make sure I did not change your meaning anywhere?
thanks!

**Comment by cjschroder** [comment]
Merging for easier editing.

**Comment by cjschroder** [comment]
I introduced a markup error that broke the build. Didn't need to merge yet, oh well. See the new PR at https://github.com/SUSE/doc-sle/pull/622
@rhafer

**Comment by rhafer** [comment]
> Hello @rhafer, thank you for this! I made a few changes, corrected some markup and smoothing out some of the wording. Will you take a look and make sure I did not change your meaning anywhere?

Thanks for those adjustments. It reads a lot better now :)

**Pull request merged**
